### ISSUE TITLE
Better naming of skills

### ISSUE THREAD

**Issue by lizgzil** [nestauk/skills-taxonomy-v2#70]
After #69 re-running extracting skills on a better sample of job adverts:
- [x] Better naming of the clusters - clean text a bit more before creating the n-grams. For example, there are instances where the name includes the singular and plural of the same word and so I think we could try some more cleaning.
- [x] Look into making sure there is only one unique name per skill.
- [x] Investigate merging the skills here. Are some of the skill clusters very small and very close together so could be merged?

**Comment by india-kerle** [comment]
given that we are adding a manual component to renaming duplicate skill cluster names, we're gonna wanna budget for that time-wise.
